### ISSUE TITLE
Single Page Limitation 

### ISSUE THREAD

**Issue by KnoDoctor** [LiveDuo/destack#24]
I've been playing around with destack and was hoping it would be possible to add support for multiple pages. Currently it appears that all instances of the editor relate back to the same content limiting the use cases to a single landing page per nextjs project. 

Great work so far and thanks in advance :)

Ps Happy to help out with any testing once this has been implemented 👍

**Comment by JcdeA** [comment]
It should be possible to implement multiple pages, I might make a PR some time for it. We just have to make an array with all the elements, separated by pages in ./data/index.ts.

**Comment by LiveDuo** [comment]
@JcdeA I've been thinking about multiple pages and came to two possible implementations.

### Possible Solutions

1. **Have multiple json files** in the data folder.

  Structure:
- data/default.json 
- data/contact.json 
- data/blog/first-post.json OR data/blog-first-post.json

👍 Backwards compatible
👍 Possibly easier to implement (not have to rewrite the JSON file each time a different page is changed)
👍 More close to what we have atm

2. **Have a single json file** as we do now but instead of having an object to have an array. In that case each element in the array would represent a page.

  Structure:
- data/default.json 

👍 Less files to commit in git

### Implementation (Solution 1)

1. We can get the [pathname](https://nextjs.org/docs/api-reference/next/router#userouter) from the router and send it with  [handleEvents](https://github.com/LiveDuo/destack/blob/main/lib/destack/src/lib/events/index.ts) to [handle](https://github.com/LiveDuo/destack/blob/main/lib/destack/server/api/handle.ts) function (so it knows where to save each page).
2. At that point we can parse the `pathname` and save the page to that path eg. pathname = `blog/first-post` will save to a `first-blog.json` in folder name `blog` (or to a `blog-first-blog.json` file)
3. We will have to change [loadTemplate](https://github.com/LiveDuo/destack/blob/main/lib/destack/src/components/initEditor.tsx) a little to account for multiple files.
4. Lastly, we will need to support multiple files in [getStaticProps](https://github.com/LiveDuo/destack/blob/main/lib/destack/server/props/index.ts) so we have the props available when the site is statically built for production!

_Note:_ An open question is what to do with [dynamic-routes](https://nextjs.org/docs/routing/dynamic-routes).
