### ISSUE TITLE
Blank builder page after refreshing the builder page, locally.

### ISSUE THREAD

**Issue by fvadouko** [LiveDuo/destack#46]
Hey, 

All the times, I do npm run dev, all I get is a blank builder page, after having build a page with the components.  While, I see in the default.json the generated code and these updates. 

Is there anything, i forget in the setup, like a env file or anything?

**Comment by LiveDuo** [comment]
Hi @fvadouko, 

There a bugs with Destack are now fixed with version `0.12.0`. 

You can try the latest version by either running `npm i destack@latest` or by using the updated [destack-starter](https://github.com/LiveDuo/destack-starter) repo.

Let me know if this fixes your issue. If it doesn't it would help to share a repository that reproduces the issue along with some information in about the system you are having issues on (OS, node version etc.).
