### ISSUE TITLE
Picking colors

### ISSUE THREAD

**Issue by augustofretes** [LiveDuo/destack#74]
Hi! I'm trying to add a color picker to destack. I made a couple of changes to text.tsx on a fork, I essentially added colors to props, and then I thought of creating an analogous to ButtionDialog.tsx, TextColorPickerDialog.tsx . Do you think this is the right approach? The reason I ask is because I know destack is pulling colors from the themes directly, e.g. bg-indigo-600.

**Comment by LiveDuo** [comment]
@augustofretes I think it's fine. There are two approaches:
a) Override the CSS styles
b) Override the CSS classes

I think the first approach ie. the one you chosen is cleaner, more flexible because you can choose any colour or add custom logic to the colour picker. Only advantage to 2nd method I see is better coherency by restricting user to only choose selected classes/colours.
